In [3]:
import numpy as np
import pandas as pd


In [4]:
data.head()

age  income  spending_score  target
0   56   54674              44       0
1   69   55854              49       0
2   46   66271              75       1
3   32   93688              61       1
4   60   58518              67       0

### working principle of KNN is , suppose If i have a new datapoint X_test[i] then it will calculate the distance of all the training data from this point and , the 'K' number of data points with closest distance from the test data it will consider those

In [9]:
class Knn:
    def __init__(self,k=3):
        self.k=k

    def fit(self,X_train,y_train):
        self.X_train=X_train
        self.y_train=y_train

    def predict(self,X_test):
        pass

    def _predict(self,x):
        #distance of all the training points from the test point
        distances=np.linalg.norm(self.X_train-x,axis=1)
        #then we will find 'K' points with min distances -> 'k' indices where dist is minimum
        k_indices=np.argsort(distances)[:self.k]
        #picking those index values from X_train
        closest_points = self.X_train[k_indices]
        #equivalent indices value we will pick from Y_train
        k_nearest_labels = self.y_train[k_indices]
        #if [0,1,1,1,0] then counts=[2,3] ## 0 appears 2 times, 1 appears 3 times
        counts = np.bincount(k_nearest_labels)
        #this will return 1 as max element 3 is at index 1
        most_common = counts.argmax()
        return most_common

    def predict(self,X_test):
        return np.array([self._predict(x) for x in X_test])


        
        

####  np.argsort is soting the indices, based on their index values

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [11]:
X=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

In [12]:
X

array([[    56,  54674,     44],
       [    69,  55854,     49],
       [    46,  66271,     75],
       ...,
       [    62,  95897,     31],
       [    35, 101905,     60],
       [    55,  88577,     60]])

In [13]:
 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [14]:
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

In [15]:
X_train

array([[-0.12149869,  1.09560164, -1.5276289 ],
       [-1.4818759 , -1.49391776, -0.61784963],
       [ 1.4429351 ,  0.19539349,  0.46040728],
       ...,
       [ 0.49067105, -0.79440093, -0.88741386],
       [ 1.30689738, -1.12107619, -0.51676305],
       [-0.12149869, -1.43996437, -1.22436915]])

In [34]:
knn=Knn(k=2)

In [35]:
knn.fit(X_train,y_train)

In [36]:
y_pred=knn.predict(X_test)

In [37]:
from sklearn.metrics import accuracy_score

In [38]:
print(accuracy_score(y_test,y_pred))

0.955


In [31]:
X_test[0]

array([-1.4818759 , -1.27177719,  0.22453858])

In [32]:
y_test[0]

0

In [33]:
y_pred[0]

0